<?php
/**
 * Handles the Loading and setting of the ACF fields for the plugin
 *
 * @since 1.0
 * @package ChoctawNation
 */

add_action(
	'acf/include_fields',
	function () {
		if ( ! function_exists( 'acf_add_local_field_group' ) ) {
				return;
		}

		acf_add_local_field_group(
			array(
				'key'                   => 'group_61df393e4acc4',
				'title'                 => 'Boilerplate',
				'fields'                => array(
					array(
						'key'               => 'field_61df393e67b9f',
						'label'             => 'About',
						'name'              => 'about_company',
						'aria-label'        => '',
						'type'              => 'wysiwyg',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'tabs'              => 'all',
						'toolbar'           => 'full',
						'media_upload'      => 1,
						'delay'             => 0,
					),
					array(
						'key'               => 'field_61df393e67ba5',
						'label'             => 'Media Inquiry',
						'name'              => 'media_inquiry',
						'aria-label'        => '',
						'type'              => 'wysiwyg',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'tabs'              => 'all',
						'toolbar'           => 'full',
						'media_upload'      => 1,
						'delay'             => 0,
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'choctaw-boilerplates',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'acf_after_title',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => 'Handles Boilerplate content creation for News CPT posts.',
				'show_in_rest'          => 1,
			)
		);

		acf_add_local_field_group(
			array(
				'key'                   => 'group_6337162e75a4e',
				'title'                 => 'News Single',
				'fields'                => array(
					array(
						'key'               => 'field_633c9a62ea11e',
						'label'             => 'Featured Post?',
						'name'              => 'featured_post',
						'aria-label'        => '',
						'type'              => 'true_false',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'message'           => '',
						'default_value'     => 0,
						'ui_on_text'        => '',
						'ui_off_text'       => '',
						'ui'                => 0,
					),
					array(
						'key'               => 'field_6356dc83eee55',
						'label'             => 'Subheading',
						'name'              => 'subheading',
						'aria-label'        => '',
						'type'              => 'text',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => '',
						'placeholder'       => '',
						'prepend'           => '',
						'append'            => '',
					),
					array(
						'key'               => 'field_6543a1f7285a8',
						'label'             => 'Photo Meta',
						'name'              => 'photo_meta',
						'aria-label'        => '',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'block',
						'sub_fields'        => array(
							array(
								'key'               => 'field_6356dc8beee56',
								'label'             => 'Photo Credit',
								'name'              => 'photo_credit',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
							),
							array(
								'key'               => 'field_6356dc96eee57',
								'label'             => 'Photo Caption',
								'name'              => 'photo_caption',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
							),
						),
					),
					array(
						'key'               => 'field_635833b25f2ce',
						'label'             => 'Article',
						'name'              => 'article',
						'aria-label'        => '',
						'type'              => 'wysiwyg',
						'instructions'      => '',
						'required'          => 1,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'delay'             => 0,
						'tabs'              => 'all',
						'toolbar'           => 'full',
						'media_upload'      => 1,
					),
					array(
						'key'                  => 'field_6356bad640d83',
						'label'                => 'Additional Boilerplates',
						'name'                 => 'additional_boilerplates',
						'aria-label'           => '',
						'type'                 => 'relationship',
						'instructions'         => '',
						'required'             => 0,
						'conditional_logic'    => 0,
						'wrapper'              => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'post_type'            => array(
							0 => 'choctaw-boilerplates',
						),
						'taxonomy'             => '',
						'filters'              => array(
							0 => 'search',
						),
						'return_format'        => 'object',
						'min'                  => '',
						'max'                  => '',
						'elements'             => '',
						'bidirectional_target' => array(),
					),
					array(
						'key'               => 'field_6356e4ff33288',
						'label'             => 'Full Article Link (optional)',
						'name'              => 'full_article',
						'aria-label'        => '',
						'type'              => 'group',
						'instructions'      => '',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'layout'            => 'block',
						'sub_fields'        => array(
							array(
								'key'               => 'field_6543a271285ab',
								'label'             => 'Read Full Article Link',
								'name'              => 'has_link_to_full_article',
								'aria-label'        => '',
								'type'              => 'true_false',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => 0,
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'message'           => 'Show options to create link to full, external article',
								'default_value'     => 0,
								'ui'                => 0,
								'ui_on_text'        => '',
								'ui_off_text'       => '',
							),
							array(
								'key'               => 'field_6356e64533289',
								'label'             => 'Article Title',
								'name'              => 'title',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => array(
									array(
										array(
											'field'    => 'field_6543a271285ab',
											'operator' => '==',
											'value'    => '1',
										),
									),
								),
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
							),
							array(
								'key'               => 'field_6356e6503328a',
								'label'             => 'Article Link',
								'name'              => 'link',
								'aria-label'        => '',
								'type'              => 'url',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => array(
									array(
										array(
											'field'    => 'field_6543a271285ab',
											'operator' => '==',
											'value'    => '1',
										),
									),
								),
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'placeholder'       => '',
							),
							array(
								'key'               => 'field_6356e65f3328b',
								'label'             => 'Article Author',
								'name'              => 'author',
								'aria-label'        => '',
								'type'              => 'text',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => array(
									array(
										array(
											'field'    => 'field_6543a271285ab',
											'operator' => '==',
											'value'    => '1',
										),
									),
								),
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'default_value'     => '',
								'maxlength'         => '',
								'placeholder'       => '',
								'prepend'           => '',
								'append'            => '',
							),
							array(
								'key'               => 'field_6356e66a3328c',
								'label'             => 'Article Published Date',
								'name'              => 'published_date',
								'aria-label'        => '',
								'type'              => 'date_picker',
								'instructions'      => '',
								'required'          => 0,
								'conditional_logic' => array(
									array(
										array(
											'field'    => 'field_6543a271285ab',
											'operator' => '==',
											'value'    => '1',
										),
									),
								),
								'wrapper'           => array(
									'width' => '',
									'class' => '',
									'id'    => '',
								),
								'display_format'    => 'F j, Y',
								'return_format'     => 'M j, Y',
								'first_day'         => 0,
							),
						),
					),
					array(
						'key'               => 'field_635833e45f2cf',
						'label'             => 'Video',
						'name'              => 'video',
						'aria-label'        => '',
						'type'              => 'number',
						'instructions'      => 'Videos must be public!',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'min'               => '',
						'max'               => '',
						'placeholder'       => '',
						'step'              => '',
						'prepend'           => 'https://vimeo.com/',
						'append'            => '',
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'choctaw-news',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'acf_after_title',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => 'News CPT Fields, including relationship to Boilerplate CPT',
				'show_in_rest'          => 1,
			)
		);

		acf_add_local_field_group(
			array(
				'key'                   => 'group_6543a3912397b',
				'title'                 => 'News Single - Sidebar',
				'fields'                => array(
					array(
						'key'               => 'field_6543a3915e1c0',
						'label'             => 'Brief Description',
						'name'              => 'archive_content',
						'aria-label'        => '',
						'type'              => 'textarea',
						'instructions'      => 'Character limit 155. New lines ignored.',
						'required'          => 0,
						'conditional_logic' => 0,
						'wrapper'           => array(
							'width' => '',
							'class' => '',
							'id'    => '',
						),
						'default_value'     => '',
						'maxlength'         => 155,
						'rows'              => '',
						'placeholder'       => '',
						'new_lines'         => '',
					),
				),
				'location'              => array(
					array(
						array(
							'param'    => 'post_type',
							'operator' => '==',
							'value'    => 'choctaw-news',
						),
					),
				),
				'menu_order'            => 0,
				'position'              => 'side',
				'style'                 => 'default',
				'label_placement'       => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen'        => '',
				'active'                => true,
				'description'           => 'Displays the Yoast SEO "archive content" / Excerpt in the sidebar. Character limit: 155.',
				'show_in_rest'          => 1,
			)
		);
	}
);
